name: Cache Cleanup

on:
  schedule:
    # Run every Sunday at 02:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Clean up old caches

    steps:
      - name: Cleanup old caches
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            // Get all caches
            const caches = await github.rest.actions.getActionsCacheList({
              owner,
              repo,
              per_page: 100
            });

            console.log(`Found ${caches.data.total_count} caches`);

            // Calculate cutoff date (7 days ago)
            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - 7);

            let deletedCount = 0;

            for (const cache of caches.data.actions_caches) {
              const cacheDate = new Date(cache.last_accessed_at);

              if (cacheDate < cutoffDate) {
                try {
                  await github.rest.actions.deleteActionsCacheById({
                    owner,
                    repo,
                    cache_id: cache.id
                  });

                  console.log(`Deleted cache: ${cache.key} (last accessed: ${cache.last_accessed_at})`);
                  deletedCount++;
                } catch (error) {
                  console.error(`Failed to delete cache ${cache.key}:`, error.message);
                }
              }
            }

            console.log(`Cleanup completed. Deleted ${deletedCount} old caches.`);

            // Also clean up old Playwright browser caches specifically
            const playwrightCaches = caches.data.actions_caches.filter(cache =>
              cache.key.includes('playwright') && new Date(cache.last_accessed_at) < cutoffDate
            );

            if (playwrightCaches.length > 0) {
              console.log(`Found ${playwrightCaches.length} old Playwright caches to clean up`);
            }