name: CI Tests

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run tests
        run: pnpm test

  playwright:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: E2E Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup with Playwright
        uses: ./.github/actions/setup-with-playwright

      - name: Build client
        run: pnpm --filter client build

      - name: Start server
        run: pnpm --filter client preview &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:5173 --timeout 30000

      - name: Run Playwright functional tests
        run: pnpm --filter client test:e2e:functional

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30