name: PR checks

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Check formatting
        run: pnpm format:check

  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Check linting
        run: pnpm lint:check

  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm

      - name: Run tests
        run: pnpm test
