name: Visual Regression Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
      - '.gitignore'

permissions:
  contents: read

jobs:
  lost-pixel:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup with Playwright
        uses: ./.github/actions/setup-with-playwright

      - name: Build client
        run: pnpm --filter client build

      - name: Start server
        run: pnpm --filter client preview &

      - name: Wait for server
        run: npx wait-on http://127.0.0.1:5173 --timeout 30000

      - name: Create lost-pixel directory
        run: mkdir -p client/lost-pixel

      - name: Run Playwright tests
        run: pnpm --filter client test:e2e:visual

      - name: Copy Lost Pixel config to root
        run: cp client/lostpixel.config.ts ./lostpixel.config.ts

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.22.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: visual-test-screenshots
          path: client/lost-pixel/
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-visual
          path: client/playwright-report/
          retention-days: 30
