name: Visual Regression Tests

on: [pull_request]

jobs:
  lost-pixel:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build client
        run: pnpm --filter client build

      - name: Start server
        run: pnpm --filter client preview &

      - name: Wait for server
        run: npx wait-on http://172.17.0.1:4173 --timeout 30000

      - name: Install Playwright browsers
        run: pnpm --filter client test:e2e:install:ci

      - name: Run Playwright tests
        run: pnpm --filter client test:e2e:visual

      - name: Create lost-pixel directory if it doesn't exist
        run: mkdir -p client/lost-pixel

      - name: Copy Lost Pixel config to root
        run: cp client/lostpixel.config.ts ./lostpixel.config.ts

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.22.0
        env:
          LOST_PIXEL_API_KEY: ${{ secrets.LOST_PIXEL_API_KEY }}
